### ISSUE TITLE
Exception: undefined local variable or method `env`.

### ISSUE THREAD

**Issue by mirek** [ambethia/recaptcha#249]
```
Exception Recaptcha::RecaptchaError in Rack application object (undefined local variable or method `env' for #<#<Class:0x00005593a1e55f08>:0x00005593a2344d48>) (process 8913, thread 0x00005593a17eb6b8(Worker 1)):
App 8894 stderr: 	from /usr/local/lib/ruby/gems/2.4.0/gems/recaptcha-4.6.2/lib/recaptcha/verify.rb:73:in `recaptcha_verify_via_api_call'
App 8894 stderr: 	from /usr/local/lib/ruby/gems/2.4.0/gems/recaptcha-4.6.2/lib/recaptcha/verify.rb:19:in `verify_recaptcha'
...
```

...when using it with roda/rodauth.

Can we add at the beginning of this list...
https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/verify.rb#L73
...something like:
```
(options[:remote_ip]) || ...
```
...at the beginning to avoid touching undefined `env`?

**Comment by grosser** [comment]
sounds good ... maybe even detect if env is defined and only then call it to avoid errors like this
make sure to add a test without env too

**Comment by roseliux** [comment]
I am facing with the same error and because of the `env` is not define 
I was able to get the `REMOTE_ADDR` with  `request.env['REMOTE_ADDR']`
I need help in how I can fix this or help you to fix if that's the case

**Comment by roseliux** [comment]
Yes this is happening on version 4.3.1 and I can't update the version because of other dependencies,
I am going to monkey patch the method instead, open to other suggestion.
Thanks.

**Comment by grosser** [comment]
hmm recaptcha does not have any dependencies, so updating should work fine

**Comment by roseliux** [comment]
I mean on my rails app,  It depends on this version of recaptcha.

**Comment by Akrivus** [comment]
I ran into this issues myself and fixed it by adding this method to my app's `application_helper.rb`
```ruby
def env
  request.env
end
```

**Comment by grosser** [comment]
plz make a PR for detecting if `request` is defined and then using that, afaik that's what rails apps need to work
