### ISSUE TITLE
recaptcha 4.8.1 with Rails 5.1.6 fails to start server

### ISSUE THREAD

**Issue by krsyoung** [ambethia/recaptcha#280]
I just pulled 4.8.1 and it looks like it is blowing up with rails 5.1.6 / ruby 2.5.0.  Here is the error message I get when trying to start the server:

```
Traceback (most recent call last):
	19: from bin/rails:4:in `<main>'
	18: from bin/rails:4:in `require'
	17: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	16: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	15: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	14: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	13: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	12: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	11: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	10: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	 9: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `block in perform'
	 8: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `require'
	 7: from /Users/chris/Development/app/config/application.rb:7:in `<top (required)>'
	 6: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	 5: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	 4: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	 3: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	 2: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	 1: from /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require': cannot load such file -- recaptcha/rails (LoadError)
```

If I revert to 4.8.0 everything works as expected.  Something related to the new lazy load?

**Comment by grosser** [comment]
dammit ... should not have been a patch release ... did not see all the stacked up commits on master

**Comment by grosser** [comment]
yanked 4.8.1

**Comment by krsyoung** [comment]
It happens!  Thanks for the quick response.

**Comment by grosser** [comment]
hmm I think this is a bug in a gemfile somewhere ... has a `require: 'recaptcha/rails'`

**Comment by grosser** [comment]
ah yeah that is the old setup ... I guess time to move the files back

**Comment by krsyoung** [comment]
So I guess the net here is either to update the Gemfile (if using the old recaptcha syntax):

     # old (< 4.8.1)
     gem 'recaptcha', require: 'recaptcha/rails'

     # new (>= 4.8.1)
     gem 'recaptcha'

Or wait for a 4.8.1 re-release with https://github.com/ambethia/recaptcha/pull/281 which tolerates the `require`.

I can confirm I have the (yanked) 4.8.1 working just by updating the Gemfile.

**Comment by grosser** [comment]
4.9.0
